### ISSUE TITLE
Is there a way to mask the secrets?

### ISSUE THREAD

**Issue by askb** [actions-marketplace-validations/infovista-opensource_vars-to-env-action#72]
Is there a way to mask the secrets? Without that the secrets are all visible through the workflow/job logs.

example:
```
steps:
- uses: actions/checkout@v3
- uses: infovista-opensource/vars-to-env-action@v1
  with:
    secrets: ${{ toJSON(secrets) }}
    mask: true
- run: echo "Value of MY_SECRET: $MY_SECRET"
```
